import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

const geistSans = localFont({
  src: [
    { path: "../node_modules/geist/dist/fonts/geist-sans/Geist-Variable.woff2", weight: "100 900", style: "normal" },
    { path: "../node_modules/geist/dist/fonts/geist-sans/Geist-Italic[wght].woff2", weight: "100 900", style: "italic" },
  ],
  variable: "--font-geist-sans",
  display: "swap",
  adjustFontFallback: false,
});

const geistMono = localFont({
  src: [
    { path: "../node_modules/geist/dist/fonts/geist-mono/GeistMono-Variable.woff2", weight: "100 900", style: "normal" },
    { path: "../node_modules/geist/dist/fonts/geist-mono/GeistMono-Italic[wght].woff2", weight: "100 900", style: "italic" },
  ],
  variable: "--font-geist-mono",
  display: "swap",
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "hsy的宇宙",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="zh-CN"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <link rel="preconnect" href="https://psxbkmivluagujdqnfsu.supabase.co" crossOrigin="anonymous" />
      <link rel="dns-prefetch" href="https://psxbkmivluagujdqnfsu.supabase.co" />
      <body className="min-h-full flex flex-col">{children}<Analytics /><SpeedInsights /></body>
    </html>
  );
}