import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: [
    { path: "../node_modules/geist/dist/fonts/geist-sans/Geist-Variable.woff2", weight: "100 900", style: "normal" },
    { path: "../node_modules/geist/dist/fonts/geist-sans/Geist-Italic[wght].woff2", weight: "100 900", style: "italic" },
  ],
  variable: "--font-geist-sans",
  display: "swap",
  adjustFontFallback: false,
});

const geistMono = localFont({
  src: [
    { path: "../node_modules/geist/dist/fonts/geist-mono/GeistMono-Variable.woff2", weight: "100 900", style: "normal" },
    { path: "../node_modules/geist/dist/fonts/geist-mono/GeistMono-Italic[wght].woff2", weight: "100 900", style: "italic" },
  ],
  variable: "--font-geist-mono",
  display: "swap",
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "hsy的宇宙",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}